name: ESLint
on:
  push:
    branches:
      - 'master'
      - 'indev'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
  pull_request:
    branches:
      - 'master'
      - 'indev'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - '**.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 13.x, 14.x]
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Uses Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installs all global dependencies
        run: npm i -g eslint
      - name: Installs local packages
        run: npm i
      - name: Lint the repository for code checks
        run: eslint src --ext .js --fix
